# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-22 03:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_table', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='courseName',
        ),
    ]
